### PR TITLE
Create plugin.yml

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by matthew4444** [comment]
Hey stop pull requetaing our plugins

**Comment by flaxues** [comment]
@matthew4444 He is just helping!!

**Comment by matthew4444** [comment]
Hey wanna be on the team

**Comment by erkam2002** [comment]
How join i the Gitter chat?

**Comment by matthew4444** [comment]
Yz

**Comment by matthew4444** [comment]
Ya

**Comment by erkam2002** [comment]
Where can i join gitter chat

**Pull request closed without merging**
